# Generated by Django 5.1.1 on 2024-10-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelsD',
            fields=[
                ('customerid', models.IntegerField(primary_key=True, serialize=False)),
                ('orderid', models.IntegerField()),
                ('age', models.IntegerField()),
                ('cust_no', models.IntegerField()),
                ('rate', models.IntegerField()),
            ],
        ),
    ]
