# Generated by Django 5.1.1 on 2024-09-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bankloan',
            fields=[
                ('customerid', models.IntegerField(primary_key=True, serialize=False)),
                ('customerrate', models.IntegerField()),
                ('age', models.IntegerField()),
                ('cust_no', models.IntegerField()),
                ('customerloan_purpose', models.CharField(max_length=500)),
            ],
        ),
    ]
